### ISSUE TITLE
must-read-for-neo-tantrikas.md

### ISSUE THREAD

**Issue by 10-4-5-404-NotFoundCasper** [Skeptical-Tantra/skeptical-tantra#2]
must-read-for-neo-tantrikas.md

---
title: À lire pour les Neo-Tantrikas
id: must-read-for-neo-tantrikas
sidebar_position: 1
---

Si tu pratiques déjà du Tantra et/ou du massage Tantrique, notamment avec une approche spirituelle qui se fonde notamment sur les chakras, alors, il y a de fortes chances que le contenu de ce site Web ne te parle pas. En revanche, si tu as des ami.e.s très rationnels, très Yang, qui ne croient pas à ta vision de l'énergétique, mais que tu aimerais qu'ils comprennent un peu mieux ce qu'est le Tantra, alors, tu es peut-être au bon endroit :

En effet, le but de ce site Web est d'essayer de construire un pont entre les pratiques promues par le Tantra et essayer de les rapprocher de la Science, afin de fournir du contenu qui soit compréhensible par des personnes qui n'ont pas le vocabulaire utilisé habituellement dans le Tantra et / ou qui ne sont pas en recherche de spiritualité.

Pour cela, ce site Web propose des explications alternatives à celles promues dans le Tantra, en remplaçant les explications fondées sur le New Age par des explications qui utilisent un champ lexical Scientifique, afin que ces personnes, rassurées par des explications qui reprennent un vocabulaire qui leur est familier, aient peut-être envie, d'expérimenter ***### **_le_***** Tantra.

Certaines informations peuvent être contraires à la croyance populaire dans le Tantra, voire provoquer des dissonances cognitives pour des Tantrikas New Age, nous en sommes sincèrement désolés, ce n'est pas le but recherché, il n'y a aucune obligation à adhérer aux informations présentes sur ce site Web, et il est fortement probable que des erreurs ou des mauvaises interprétations soient présentes.

Merci d'accueillir ce site Web avec bienveillance et non-jugement, comme le propose la philosophie Tantra.

**Comment by le-maitre-des-horloges** [comment]
Merci @10-4-5-404-NotFoundCasper pour la typo, changé dans la documentation: https://github.com/Skeptical-Tantra/skeptical-tantra/commit/bbeffaa34d8f456a105c3d9c9cb4596c376748a2
